version: '{build}'
branches: 
  only:
  - master
image:
- Visual Studio 2015
- Visual Studio 2017

clone_folder: c:\projects\croaring

configuration:
- Release
- Debug

platform:
- x86
- x64

init:
- set arch=
- ps: if ($Env:PLATFORM -eq "x64") { $Env:arch = "Win64" }
- ps: if ($Env:PLATFORM -eq "x86") { $Env:arch = "Win32" }
- if "%arch%"=="Win64" ( set arch= Win64)
- if "%arch%"=="Win32" ( set arch= Win32)
- echo %arch%
- echo %APPVEYOR_BUILD_WORKER_IMAGE%
- if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2017" ( set generator="Visual Studio 15 2017%arch%" )
- if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2015" ( set generator="Visual Studio 14 2015%arch%" )
- if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2013" ( set generator="Visual Studio 12 2013%arch%" )
- echo %generator%

before_build:
- cmd: >-
    dir /s

    mkdir build

    cd build

    cmake --version

    cmake -DCMAKE_GENERATOR_PLATFORM=%arch% ..    

    dir /s ..
    
build:
  project: c:\projects\croaring\build\RoaringBitmap.sln
  verbosity: detailed
  parallel: true 

