version: '{build}'
branches:
  only:
  - master
image: Visual Studio 2017

clone_folder: c:\projects\croaring

platform:
- x64

environment:
  matrix:
    - GENERATOR: "Visual Studio 15 2017" # x86 build
      AVXFLAG: "OFF"
    - GENERATOR: "Visual Studio 15 2017 Win64" # x64 build
      AVXFLAG: "OFF"
    - GENERATOR: "Visual Studio 15 2017 Win64" # x64 build
      AVXFLAG: "ON"

build_script:
  - mkdir build
  - cd build
  - ps: cmake -G "$env:GENERATOR" -DFORCE_AVX="$env:AVXFLAG" ..
  - cmake --build .
  - ctest --verbose
