version: '{build}'
branches:
  only:
  - master
image: Visual Studio 2017

clone_folder: c:\projects\croaring

platform:
- x64

environment:
  matrix:
    - GENERATOR: "Visual Studio 15 2017" # x86 build
    - GENERATOR: "Visual Studio 15 2017 Win64" # x64 build

build_script:
  - mkdir build
  - cd build
  - cmake -G %GENERATOR% ..
  - cmake --build .
  - ctest
