version: '{build}'
branches:
  only:
  - master
clone_folder: c:\projects\croaring

platform:
- x64

environment:
  matrix:
    - image:      Visual Studio 2017
      GENERATOR: "Visual Studio 15 2017" # x86 build
      AVXFLAG: "OFF"
    - image:      Visual Studio 2017
      GENERATOR: "Visual Studio 15 2017 Win64" # x64 build
      AVXFLAG: "OFF"
    - image:      Visual Studio 2017
      GENERATOR: "Visual Studio 15 2017 Win64" # x64 build
      AVXFLAG: "ON"
    - image:      Visual Studio 2015
      GENERATOR: "Visual Studio 14 2015" # x86 build
      AVXFLAG: "OFF"
    - image:      Visual Studio 2015
      GENERATOR: "Visual Studio 14 2015 Win64" # x64 build
      AVXFLAG: "OFF"
    - image:      Visual Studio 2015
      GENERATOR: "Visual Studio 14 2015 Win64" # x64 build
      AVXFLAG: "ON"

build_script:
  - mkdir build
  - cd build
  - ps: cmake -G "$env:GENERATOR" -DFORCE_AVX="$env:AVXFLAG" ..
  - cmake --build .
  - ctest --verbose
