version: '{build}'
branches:
  only:
  - master
image: Visual Studio 2017

clone_folder: c:\projects\croaring

configuration:
- Release
- Debug

platform:
- x86
- x64

matrix:
  allow_failures:
    - platform: x86

init:
- set genplat=
- ps: if ($Env:PLATFORM -eq "x64") {$Env:genplat = "-DCMAKE_GENERATOR_PLATFORM=x64" }
- '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" %PLATFORM%'

before_build:
- cmd: >-
    mkdir build

    cd build

    cmake --version

    cmake %genplat% ..

build:
  project: c:\projects\croaring\build\RoaringBitmap.sln
  verbosity: normal
  parallel: true
