language: c
sudo: false
compiler:
  - clang

branches:
  only:
    - master

script:
- ./amalgamation.sh  && clang -march=native -O3 -std=c11  -o amalgamation_demo amalgamation_demo.c  && ./amalgamation_demo && clang++ -march=native -O3 -std=c++11 -o amalgamation_demo amalgamation_demo.cpp  && ./amalgamation_demo &&  clang -march=native -mno-sse3 -O3 -std=c11  -o amalgamation_demo amalgamation_demo.c  && ./amalgamation_demo && clang++ -march=native -mno-sse3 -O3 -std=c++11 -o amalgamation_demo amalgamation_demo.cpp  && ./amalgamation_demo
- mkdir -p buildreal && cd buildreal && cmake .. && ./tests/realdata_unit
- mkdir -p buildnox64real && cd buildnox64real && cmake .. && ./tests/realdata_unit
- mkdir -p build && cd build && cmake .. && make && make CTEST_OUTPUT_ON_FAILURE=1 test && cd .. &&  mkdir -p buildnox64 && cd buildnox64 && cmake -DDISABLE_X64=ON .. && make && make CTEST_OUTPUT_ON_FAILURE=1 test && cd .. &&  mkdir -p debugbuild && cd debugbuild && cmake -DCMAKE_BUILD_TYPE=Debug .. && make && make CTEST_OUTPUT_ON_FAILURE=1 test && cd .. &&  mkdir -p debugbuildnox64 && cd debugbuildnox64 && cmake  -DCMAKE_BUILD_TYPE=Debug  -DDISABLE_X64=ON .. && make && make CTEST_OUTPUT_ON_FAILURE=1 test
